/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/redux';


export namespace Components {

  interface MyApp {}
  interface MyAppAttributes extends StencilHTMLAttributes {}

  interface MyCarouselItem {
    'index': number;
  }
  interface MyCarouselItemAttributes extends StencilHTMLAttributes {
    'index'?: number;
  }

  interface MyCarousel {}
  interface MyCarouselAttributes extends StencilHTMLAttributes {}

  interface MyComponent {
    'first': string;
    'last': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyApp': Components.MyApp;
    'MyCarouselItem': Components.MyCarouselItem;
    'MyCarousel': Components.MyCarousel;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'my-app': Components.MyAppAttributes;
    'my-carousel-item': Components.MyCarouselItemAttributes;
    'my-carousel': Components.MyCarouselAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLMyAppElement extends Components.MyApp, HTMLStencilElement {}
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };

  interface HTMLMyCarouselItemElement extends Components.MyCarouselItem, HTMLStencilElement {}
  var HTMLMyCarouselItemElement: {
    prototype: HTMLMyCarouselItemElement;
    new (): HTMLMyCarouselItemElement;
  };

  interface HTMLMyCarouselElement extends Components.MyCarousel, HTMLStencilElement {}
  var HTMLMyCarouselElement: {
    prototype: HTMLMyCarouselElement;
    new (): HTMLMyCarouselElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'my-app': HTMLMyAppElement
    'my-carousel-item': HTMLMyCarouselItemElement
    'my-carousel': HTMLMyCarouselElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'my-app': HTMLMyAppElement;
    'my-carousel-item': HTMLMyCarouselItemElement;
    'my-carousel': HTMLMyCarouselElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
